controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointGroupTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    joints:
      - yori_joint_body
      - yori_joint_l1
      - yori_joint_l2
      - yori_joint_l3
      - yori_joint_l4
      - yori_joint_l5
      - yori_joint_r1
      - yori_joint_r2
      - yori_joint_r3
      - yori_joint_r4
      - yori_joint_r5
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      - torque